version: '3'

services:

  postgresdb:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/solution_factory_project
    ports:
      - "8001:8000"
    depends_on:
      - postgresdb

  nginxserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./static/:/static
    ports:
      - "8080:80"
    depends_on:
      - webapp
